### ISSUE TITLE
v1.1.9: An error occured while testing the downloaded ffmpeg binary

### ISSUE THREAD

**Issue by bogdanbun** [Brandawg93/homebridge-nest-cam2#25] opened 2020-03-19 16:07 UTC
I'm using a custom compiled ffmpeg version (as oppose to apt binary package). When installing the last version of homebridge-nest-cam2 (1.1.9) I get the following error:

```
~/.npm# npm -g update homebridge-nest-cam2 --unsafe-perm

> ffmpeg-for-homebridge@0.0.3 install /usr/lib/node_modules/homebridge-nest-cam2/node_modules/ffmpeg-for-homebridge
> node install.js

Downloading ffmpeg from https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-debian-x86_64.tar.gz
100% - Download Complete
/root/.npm/_ffmpeg_for_homebridge/ffmpeg: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory
An error occured while testing the downloaded ffmpeg binary.
+ homebridge-nest-cam2@1.1.9
added 16 packages from 6 contributors and updated 1 package in 4.231s
```

Apparently it is trying to install another binary and it is missing some dependency.

**Comment by bogdanbun** [comment] 2020-03-19 16:40
Looks like libmvec was introduced in glibc 2.22, and my version of Debian goes up to 2.19.

**Comment by Brandawg93** [comment] 2020-03-19 17:26
Future homebridge camera plugins will be moving to use [ffmpeg-for-homebridge](https://github.com/homebridge/ffmpeg-for-homebridge). It sounds like it's an issue with that. I would suggest submitting an issue there.

**Comment by oznu** [comment] 2020-03-19 21:19
As mentioned here https://github.com/homebridge/ffmpeg-for-homebridge/issues/2

You can install ffmpeg manually from another and the plugin will still work. I will update the "Failed to test" message with a note saying the user needs to provide their own copy of ffmpeg.

**Comment by Brandawg93** [comment] 2020-03-20 11:38
Thanks for the clarification, oznu. It looks like the plugin is working as intended and will fall back to the installed ffmpeg.

**Closed by Brandawg93** 2020-03-20 11:38 UTC
